#!/bin/bash
# A small script to automatically find and copy an exploit file to the current directory...

SEARCHSPLOIT_EXPLOITS_DIR='/usr/share/exploitdb/'
FINDSPLOIT_USER_EXPLOIT_DIRS="${FINDSPLOIT_USER_EXPLOIT_DIRS:-}"  # Set an empty string to this env var if unsed or empty
COLOR1='\033[1m\033[91m'
COLOR2='\033[1m\033[92m'
COLOR3='\033[1m'
RESET='\033[0m'

function logo {
	echo -e "$COLOR3   ___ _           _           _       _ _   "
	echo -e "$COLOR3  / __(_)_ __   __| |___ _ __ | | ___ (_) |_ "
	echo -e "$COLOR3 / _\ | | '_ \ / _\` / __| '_ \| |/ _ \| | __|"
	echo -e "$COLOR3/ /   | | | | | (_| \__ \ |_) | | (_) | | |_ "
	echo -e "$COLOR3\/    |_|_| |_|\__,_|___/ .__/|_|\___/|_|\__|"
	echo -e "$COLOR3                        |_|                  "
	echo ""
	echo -e "$COLOR1+ -- --=[findsploit by 1N3"
	echo -e "$COLOR1+ -- --=[https://crowdshield.com$RESET"
	echo ""
}

function exit_fail() {
	echo -e "$COLOR1+ -- --=[Error: $1 $RESET"
	echo ""
	exit 1
}

if [ -z "$1" ]; 
then
	logo
	echo ""
	exit;
else
	logo
	echo -e "$COLOR1+ -- --=[COPYING: $COLOR2 $1 $COLOR1 TO $COLOR2 `pwd` $RESET"
	echo -e "$COLOR1+ -- --=[Search $COLOR2 $1 $COLOR1 into $COLOR2 $SEARCHSPLOIT_EXPLOITS_DIR $FINDSPLOIT_USER_EXPLOIT_DIRS $RESET"
	echo -e "$COLOR1+ -- --=[You can put path of your exploitation kits into \$FINDSPLOIT_USER_EXPLOIT_DIRS environment variable"
	echo ""
	find $SEARCHSPLOIT_EXPLOITS_DIR $FINDSPLOIT_USER_EXPLOIT_DIRS -name $1 -exec cp -f '{}' . ';'
	echo -e "$COLOR1"
	ls -lahtr $1 2>/dev/null || exit_fail "Exploit $1 not found"
fi
exit

